export const STORE_UI = 'ui'
export const STORE_APP = 'app'
export const STORE_DATA = 'data'
export const STORE_SESSION = 'session'

// import Authentication from './Authentication'
// import FlyIns from './FlyIns'
// import LegislatorBio from './LegislatorBio'
// import Notes from './Notes'
// import PushNotification from './PushNotification'
// import AppConfig from './AppConfig'
