# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  rn_path = '../node_modules/react-native'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  # =================================
  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga"
  # =================================

  # RN pods
  # =================================
  pod 'React', :path => rn_path, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    # 'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    # 'RCTText',
    # 'RCTBlob',
    # 'RCTNetwork',
    # 'RCTWebSocket', # Needed for debugging
    # 'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # 'RCTActionSheet',
    # # 'RCTGeolocation',
    # # 'RCTCameraRoll',
    # 'RCTImage', # Add RCTImage
    # 'RCTSettings',
    # 'RCTLinkingIOS',
    # # 'RCTVibration',
    # # 'RCTPushNotification',
  ]

  # pod 'React', path: '../node_modules/react-native', subspecs: %w(
  #   Core ART CxxBridge DevSupport
  #   RCTAnimation RCTImage RCTLinkingIOS RCTNetwork
  #   RCTPushNotification RCTText RCTWebSocket
  # )
  # =================================

  # Third party deps podspec link
  # =================================
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # =================================

  # Pods for app
  # =================================
  pod 'RNFS', :path => "#{rn_path}-fs"
  pod 'RNSVG', :path => "#{rn_path}-svg"
  pod 'RNLanguages', :path => "#{rn_path}-languages"
  pod 'RNDeviceInfo', :path => "#{rn_path}-device-info"
  pod 'RNPermissions', :path => "#{rn_path}-permissions"
  pod 'RNVectorIcons', :path => "#{rn_path}-vector-icons"
  pod 'react-native-splash-screen', :path => "#{rn_path}-splash-screen"
  pod 'react-native-netinfo', :path => "../node_modules/@react-native-community/netinfo"
  # =================================
end

install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => false

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
