# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  rn_path = '../node_modules/react-native'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  # =================================
  pod 'yoga', :path => "#{rn_path}/ReactCommon/yoga"

  # RN pods
  # =================================
  pod 'React', :path => rn_path, :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTBlob',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTCameraRoll',
    'RCTImage', # Add RCTImage
    'RCTSettings',
    'RCTLinkingIOS',
    'RCTVibration',
    'RCTPushNotification',
  ]

  # pod 'React', path: rn_path, subspecs: %w(
  #   Core ART CxxBridge DevSupport
  #   RCTAnimation RCTImage RCTLinkingIOS RCTNetwork
  #   RCTPushNotification RCTText RCTWebSocket
  # )
  # =================================

  # Third party deps podspec link
  # =================================
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  # =================================

  # Pods for app
  # =================================
  pod 'RNFS', :path => "../node_modules/react-native-fs"
  pod 'RNSVG', :path => "../node_modules/react-native-svg"
  pod 'RNLanguages', :path => "../node_modules/react-native-languages"
  pod 'RNDeviceInfo', :path => "../node_modules/react-native-device-info"
  pod 'RNPermissions', :path => "../node_modules/react-native-permissions"
  pod 'RNVectorIcons', :path => "../node_modules/react-native-vector-icons"

  pod 'react-native-netinfo', :path => "../node_modules/@react-native-community/netinfo"
  pod 'react-native-splash-screen', :path => "../node_modules/react-native-splash-screen"
  # =================================

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'appTests' do
    inherit! :search_paths
  end
end

install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => false

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
